### ISSUE TITLE
Onde esta os Algoritmos?

### ISSUE THREAD

**Issue by DaviVitorio** [matheusvictor95/Algoritmos-em-Phyton#1]
Hmm... não vi seus **algoritmos**, se ainda não fez tudo bem, mas se já fez, sobe aqui pra esse repositório.
😄

**Comment by matheusvictor95** [comment]
Eu ainda não fiz pq eu tive que fazer outro curso na área de segurança, mas vou voltar a fazer o curso e quando eu terminar eu coloco os algoritmos, grande abraço
